# Generated by Django 5.0.6 on 2025-04-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=200)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PASS.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Staf',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PASS.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PASS.times'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PASS.times'),
        ),
    ]
